import Background from "@/components/Background";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Art Vault - Art Gallery | Home",
  description: "Generated by create next app",
};

export default async function HomePage(){
  return (<>
    <Background />
  </>)
}