// IMPORTAÇÕES DO NEXT
// import Link from "next/link"
import Image from "next/image"
import { Suspense } from "react"

// COMPONENTES
import ScrollLetters from "@/components/ScrollLetters"
import ArtVaultBg from "@/components/ArtVaultBg"
import ScrollImgs from "@/components/ScrollImgs"
import Footer from "@/components/Footer"

// FONTS
import { leotaroFree, satoshiLight } from "../layout"

// METADATA
import { Metadata } from "next"

//CSS
import "@/public/css/art-vault-bd.css"

export const metadata: Metadata = {
  title: "Art Vault - Your Art Gallery",
  description: "Generated by create next app",
};

export default function ArtVault_Branding(){
    return (<>
        <main className="artBd">
            <Suspense fallback={"Carregando..."}>
                <ArtVaultBg />
            </Suspense>

            <ScrollLetters
                texts={['Art That Moves The Gaze -', 'Where The Stroke Comes To Life -']} 
                velocity={100}
                className={`custom-scroll-text ${leotaroFree.className}`}
                />

            <section className="inside-gallery"><div className="container"><p className={satoshiLight.className}> (Inside Vault Art Gallery)</p></div></section>

            <section className="description-art-vault">
                <div className="container">
                    <section className={`desc-text ${satoshiLight.className}`}>
                        <svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox="0 0 24 24" fill="none" stroke="#D4AF37" strokeWidth="2" strokeLinecap="round" 
                        strokeLinejoin="round" className="lucide lucide-chevron-left-icon lucide-chevron-left"><path d="m15 18-6-6 6-6"/></svg>

                        <p>Vault Art Gallery is a leading art space in Ahmedabad, India, known for
                        promoting Indian modern and contemporary art. Founded in 1978 by Anil
                        Relia, it began as a small studio and has grown into a respected gallery
                        and serigraph studio recognized across the country.</p>

                <p>As part of the Branding and Brand Communication&apos;s course, this project
                        explored 3600 branding for Archer Art Gallery. We worked across
                        campaigns, packaging, UI/UX, social media, ad films and publication,
                        developing a cohesive visual language that reflects the gallery&apos;s identity.
                        The project also aimed to raise awareness about the serigraphy process,
                        creating an integrated brand experience that connects every touchpoint
                        from physical spaces to digital platforms.</p>
                    </section>
                </div>
            </section>

            <section className="brand-showed">
                <Image 
                    src={"/images/news.png"}
                    width={1100}
                    height={700}
                    alt="Art Vault on the News"
                    loading="eager"
                />
            </section>

            <section className="scrollImgs">
                <ScrollImgs />
            </section>

            <section className="content"></section>
        </main>
            <Footer />
    </>);
}