import { Metadata } from 'next';

import Script from 'next/script';
import LogInConfig from '@/components/LoginComponent';

export const metadata: Metadata = {
  title: "Log In - Art Vault",
  description: "Generated by create next app",
};

export default function LogInPage(){
  return (<>
      <LogInConfig />
      
      <Script src='/js/login.interactions.js'></Script>
  </>)
}