import { Metadata } from 'next';

import "@/public/css/login.css"
import Script from 'next/script';
import LoginConfig from '@/components/LoginComponent';

export const metadata: Metadata = {
  title: "Log In - Art Vault",
  description: "Generated by create next app",
};

export default function Login(){
  return (<>
      <LoginConfig />
      <Script src='/js/login.interactions.js'></Script>
  </>)
}