import "@/public/css/signUp.css"
import Script from 'next/script';
import SingUpComponent from "@/components/SignUpComponent";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sign Up - Art Vault",
  description: "Generated by create next app",
};

export default function SignUp() {
    return (<>
        <SingUpComponent />
        <Script src='/js/login.interactions.js'></Script>
    </>)
};